warnings_are_errors: false
notifications:
  slack:
    secure: rzSFPbFzjllSVLVXyATQVTo1EL9RZ+gexPiOWMvSMjDpT65En47AhEjQdzZpugaIhihQbwHz0wnUZc+0f2Yeo5Dz7Y9jeRPaSL8TPjyujZUAJjodd3tusj3nncsDjHtoposKa/A8f3Im2l08tbxeQosK6nMRQUPA7JRgDfDosJ4J9X/PrkD62q4rO2+6TBPNbN12NQQ85c89xPvMVkDshXp6ALIX672TqKcBN0GVqsGXHARnh2JV8RZzzjZLKJfdwo8CzR5b++07FTfl4+PfNkNHdGEkM7xFLgoWEOCtvlQv7EqZJd006H816NSzQ4jMAaCpqvym74FA6SnN42FPj7jQUsVxVmnAfs/j4ixOjqQUxFD2jrtPlHbj3LBTveRiVBWeFqxQWWYTy+6j/Boiz23wejswGsGOR6xfVqlW1of0PvalLfByDQS94QGMkA8fjhFbSrlI9NwfKwmNAAS9dEU4x0mW4Q3FEY3e1fe48KuroTB820ncGuNWDWQzcr+ZKR/CyiOdSQvMIqwfPBJIiMx94RAS++R6TBePc80wmpSmIUY0KewuTevoRrXEYEMS2uq3tb8DJKHvN1n3bN5zaWgjqw8w+mnZ2A7ztjY8+BFcpfHtBfUbtRyGqLDCC877o/9shIln4a5eFR1zc35xNI0S+f0auSkPe9E0GjdtBIQ=
  email: false
language: python
sudo: required
dist: xenial
python: '3.7'
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate big-data-club
script:
- python test/test.py
