name: big-data-club
channels:
  - javascript
dependencies:
  - python=3.7
  - pip:
    - cloudpickle
    - beautifulsoup4
    - flask
    - matplotlib
    - nltk
    - requests
    - sklearn
  - pandas
  - jupyter
